### ISSUE TITLE
ページの一覧がエラーで表示されない

### ISSUE THREAD

**Issue by mikoim** [logue/pukiwiki_adv#49]
https://github.com/logue/pukiwiki_adv/commit/9ea42b7e7598a9a8416ad6f95930eb04d4a581ae

```
PHP Fatal error:  Uncaught Error: Call to undefined function PukiWiki\Text\open_basedir() in /home/web/a/wiki-common/lib/PukiWiki/Text/MeCab.php:24
Stack trace:
#0 /home/web/a/wiki-common/lib/PukiWiki/Text/Reading.php(53): PukiWiki\Text\MeCab->__construct('/opt/mecab/bin/...')
#1 /home/web/a/wiki-common/lib/PukiWiki/Listing.php(73): PukiWiki\Text\Reading::getReading('\xE3\x81\xA8\xE3\x81\x86\xE3\x81\xBB\xE3\x81\x86\xE3\x83\x8D...')
#2 /home/web/a/wiki-common/lib/PukiWiki/Listing.php(117): PukiWiki\Listing::getHeadings('wiki')
#3 /home/web/a/wiki-common/plugin/list.inc.php(89): PukiWiki\Listing::get('wiki', 'read')
#4 [internal function]: plugin_list_action()
#5 /home/web/a/wiki-common/lib/PukiWiki/Renderer/PluginRenderer.php(331): call_user_func('plugin_list_act...')
#6 /home/web/a/wiki-common/lib/init.php(395): PukiWiki\Renderer\Plug
```

---

もしかして

```php
// open_basedir($PATH)
ini_set('open_basedir', $PATH);
```

とは言え，open_basedirをMeCabのパスにすると今度は絞り過ぎで動作しなくなりますが…

**Comment by logue** [comment]
pukiwiki.ini.phpの$mecab_pathの値を空白にしてみてください。

**Comment by mikoim** [comment]
確かに ```$mecab_path``` を空白にするか，```open_basedir``` の下りを除去すればページ一覧を表示することが出来ます．
どういった意図で ```open_basedir($mecab_path)``` されているのかな，と思いまして．

**Comment by logue** [comment]
xreaサーバーでmecabが標準で使えるので当時あったサンプルソースをそのまま使いました。これは、その名残です。たしかに、open_basedirは謎です・・・。
